version: '3.1'

services:

  backend:
    restart: always
    build: ./backend
    ports:
      - 3000:3000

  frontend:
    depends_on:
      - "backend"
    build: ./frontend
    ports:
      - "80:80"
