name: Deploy Server to Heroku

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
    branch:
      - deploy/heroku
  workflow_dispatch:

jobs:
  heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "quiz-laurea-gabri-backend"
          heroku_email: "ledmington.dev@gmail.com"
          #usedocker: true
