name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/Ledmington/quiz-laurea-gabri.git && \
            cd quiz-laurea-gabri && \
            git config --global user.name "GitHub Action" && \
            git config --global user.email "github-action@users.noreply.github.com" && \
            cp -r backend/ /tmp && \
            git checkout deploy/heroku && \
            git pull && \
            cp -r /tmp/backend . && \
            git add . && \
            git commit -m "push $(date '+%y%m%d%H%M')" && \
            git push
