name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'Ledmington'
          repository: 'quiz-laurea-gabri'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: checkout branch deploy/heroku
        run: cd quiz-laurea-gabri && git checkout deploy/heroku
      
      - name: rebase
        run: git rebase -Xours master
      
      - name: Delete all unnecessary files
        run: rm -rf .gitignore .gitattributes README.md docker-compose.yml frontend && mv backend/* . && rm -rf backend

      - name: git config
        run: git config user.name "GitHub Actions script" && git config user.email "github.actions@fake.com"

      - name: commit and push
        run: git add . && git commit -m "push $(date '+%y%m%d%H%M')" && git push
