name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          token: '${{ secrets.GITHUB_TOKEN }}'
      - run: |
          git clone https://github.com/Ledmington/quiz-laurea-gabri.git && \
            cd quiz-laurea-gabri && \
            cp -r backend/ /tmp && \
            git checkout deploy/heroku && \
            git pull && \
            cp -r /tmp/backend . && \
            git add . && \
            git commit -m "push $(date '+%y%m%d%H%M')" && \
            git push
