name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        run: git clone https://github.com/Ledmington/quiz-laurea-gabri.git && cd quiz-laurea-gabri && ls -la

      - name: git config
        run : ls -la && git init && git config user.name "GitHub Actions script" && git config user.email "github.actions@fake.com"
      
      - name: Delete all unnecessary files
        run: ls -la && rm -rf .gitignore .gitattributes README.md docker-compose.yml frontend .github && ls -la && mv backend/* . && ls-la && rm -rf backend

      - name: checkout branch deploy/heroku and rebase
        run: git checkout deploy/heroku && git remote add origin https://github.com/Ledmington/quiz-laurea-gabri.git
      
      - name: commit and push
        run: git add . && git commit -m "push $(date '+%y%m%d%H%M')" && git push --set-upstream=origin deploy/heroku
